### ISSUE TITLE
Font also available in  other format?

### ISSUE THREAD

**Issue by KermanGreem** [kulson/William-Lin-Font#2]
Could you maybe also provide the font in other formats, as e.g. `.tff`, unfortunately my laptop isn't able to  use the `.fon` format.

**Comment by bruunioo** [comment]
Unfortunately this font is only available on windows, cause it's font created by microsoft.

**Comment by mcnuggetsx20** [comment]
8514oem.otb uploaded after a while of delay :)
Closing.
