### ISSUE TITLE
Linux font not scalable

### ISSUE THREAD

**Issue by Congstarrr** [kulson/William-Lin-Font#3]
Can it be that the linux font is a bit broken? It seems that I can't use any other size than 14pt

**Comment by bruunioo** [comment]
Unfortunately there is only one size of this font on linux

**Comment by mcnuggetsx20** [comment]
We feel you man but the thing is, this font is really old and even the windows version doesn't work very well with different sizes. We might edit it in the future to make it a little bit more scalable but for now it is what it is.
